name: CI-CD-py

on:
  push:
    branches: [main]

  workflow_dispatch:
 

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Python script
        run: python RUN.py
